// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20221211104053_FinalUpdate")]
    partial class FinalUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarOrder", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CarOrder");
                });

            modelBuilder.Entity("DataAccess.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("StoKMh")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 2,
                            Description = "The F8 Spider’s greatest achievement is the fact that it unleashes its power instantaneously with zero turbo lag, whilst retaining this V8’s unique and very special soundtrack.",
                            ImagePath = "https://i.wpimg.pl/1920x0/m.autokult.pl/ferrari-f8-spider-4-be8031ebb9c0.jpg",
                            Model = "F8 Spider",
                            Price = 450m,
                            StoKMh = 2.1000000000000001
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 10,
                            Description = "The Ferrari Portofino M’s engine belongs to the V8 turbo family voted “International Engine of the Year” on four consecutive occasions. The power unit can punch out 620 cv, 20 more than the Ferrari Portofino, thanks to new cam profiles and the introduction of a new speed sensor on the turbocharger assembly to measure the turbine revolutions. A new Gasoline Particulate Filter allows the car to comply with the strictest European anti-pollution standards (Euro-6D) without compromising driving pleasure.",
                            ImagePath = "https://ocdn.eu/images/pulscms/MTE7MDA_/a4ee38a1d3741562afa4faa20746f704.jpg",
                            Model = "Ferrari Portofino M",
                            Price = 420m,
                            StoKMh = 3.4500000000000002
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 5,
                            Description = "To maintain the traditional, incredibly high standard of engine sound whilst simultaneously introducing a GPF (Gasoline Particulate Filter), a new exhaust tailpipe was added. This design solution reinstates medium-high frequency sound. In order to deliver excellent acoustics, performance and aesthetics, the exhaust tailpipes are visible to underscore their function and the car’s track-inspired character. The addition of a second pair of resonators enhances the engine’s more noble combustion order harmonics, creating the perfect melding of the sound from the exhaust and from the intake system.",
                            ImagePath = "https://profiauto.pl/blog/wp-content/uploads/2021/05/Ferrari-812-Competizione.jpg",
                            Model = "FERRARI 812 COMPETIZIONE",
                            Price = 430m,
                            StoKMh = 2.8999999999999999
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 5,
                            Description = "Exactly 50 years on from the debut of the last spider in the Ferrari range to sport a front-mounted V12, the 812 GTS hails a triumphant return for a model type that has played a pivotal role in the marque’s history since its foundation.",
                            ImagePath = "https://profiauto.pl/blog/wp-content/uploads/2022/05/Ferrari-SP48-Unica.jpg",
                            Model = "Ferrari 812 GTS",
                            Price = 480m,
                            StoKMh = 3.0
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 8,
                            Description = "From the outside, the design of the Ferrari 296 GTB borrows heavily from the larger SF90 as well as the classic 1960s Ferrari 250 LM.",
                            ImagePath = "https://profiauto.pl/blog/wp-content/uploads/2021/06/Ferrari-296-GTB-hybryda-z-V6.jpg",
                            Model = "Ferrari 296 GTB",
                            Price = 470m,
                            StoKMh = 2.5
                        },
                        new
                        {
                            Id = 6,
                            ColorId = 7,
                            Description = "The sky overhead appears just 14 seconds after pressing the button, and the entire operation of opening and folding the roof can be carried out while driving.",
                            ImagePath = "https://profiauto.pl/blog/wp-content/uploads/2020/11/Ferrari-SF90-Spider-hybryda-plug-in-z-napedem-na-4-kola-i-moca-1000-KM.jpg",
                            Model = "Ferrari SF90 Spider",
                            Price = 500m,
                            StoKMh = 2.75
                        },
                        new
                        {
                            Id = 7,
                            ColorId = 5,
                            Description = "Thanks to the changes made, the Ferrari SF90 Stradale produces 780 hp and 800 Nm of torque. An additional 217 hp is provided by three electric motors - two located at the front and one located between the engine and gearbox. The total power of the propulsion system is reportedly 1000 hp.",
                            ImagePath = "https://profiauto.pl/blog/wp-content/uploads/2019/05/Ferrari-SF90-Stradale.jpg",
                            Model = "Ferrari SF90 Stradale",
                            Price = 490m,
                            StoKMh = 2.6499999999999999
                        },
                        new
                        {
                            Id = 8,
                            ColorId = 3,
                            Description = "Pista is Italian for track. This nickname was given by Ferrari to the successor of the 458 Speciale, revealing its main asset at the outset. Ladies and gentlemen, this is the Ferrari 488 Pista.",
                            ImagePath = "https://profiauto.pl/blog/wp-content/uploads/2018/02/Ferrari-488-Pista.jpg",
                            Model = "Ferrari 488 Pista",
                            Price = 510m,
                            StoKMh = 3.1000000000000001
                        },
                        new
                        {
                            Id = 9,
                            ColorId = 1,
                            Description = "To improve high-speed stability, the Ferrari F8 Spider features a two-piece carbon fiber front spoiler. Carbon has also been spared on the door handles, mirrors, engine cover and rear wing. The entire bodywork was fine-tuned for aerodynamics in the wind tunnel.",
                            ImagePath = "https://profiauto.pl/blog/wp-content/uploads/2021/09/Ferrari-F8-Spider-Novitec.jpg",
                            Model = "Ferrari F8 Spider Novitec",
                            Price = 415m,
                            StoKMh = 2.7999999999999998
                        },
                        new
                        {
                            Id = 10,
                            ColorId = 3,
                            Description = "Particularly noteworthy is the rear fins, which dissipate heat from the engine compartment and, together with the powerful diffuser, provide the right downforce. At a speed of 200 km/h, it is as much as 240 kg.",
                            ImagePath = "https://profiauto.pl/blog/wp-content/uploads/2021/11/Ferrari-Daytona-SP3.jpg",
                            Model = "Ferrari Daytona SP3",
                            Price = 560m,
                            StoKMh = 2.0
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Space Gray"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 4,
                            Name = "White"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lime"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Aqua"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gray"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarOrder", b =>
                {
                    b.HasOne("DataAccess.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Car", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Car", b =>
                {
                    b.HasOne("DataAccess.Entities.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");
                });

            modelBuilder.Entity("DataAccess.Entities.Order", b =>
                {
                    b.HasOne("DataAccess.Entities.User", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Color", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
